### ISSUE TITLE
Distro packaging: releases

### ISSUE THREAD

**Issue by kuruczgy** [mstoeckl/swaylock-plugin#12]
Hi! I am a happy user of this project, and it would be even better if I didn't have to compile it for myself :) Any chance you could start doing releases so it could get packaged in distros more easily?

**Comment by mstoeckl** [comment]
I've tagged a release; see https://github.com/mstoeckl/swaylock-plugin/releases/tag/v1.8.0. Since `swaylock-plugin` closely follows upstream `swaylock` in behavior (I cherry-pick in all applicable commits), I plan to make a new release whenever `swaylock` itself makes one.
